export const SEARCH_CITY_STARTED = 'SEARCH_CITY_STARTED';
export const SEARCH_CITY_SUCCEEDED = 'SEARCH_CITY_SUCCEEDED';
export const SEARCH_CITY_FAILED = 'SEARCH_CITY_FAILED';

export const SELECT_PAGE_SIZE = 'SELECT_PAGE_SIZE';
